# config/packages/security.yaml
security:
    # enable_authenticator_manager: true
    # ...
    # config/packages/security.yaml
    providers:
        app_user_provider:
            id: App\Security\UserProvider

    password_hashers:
        # Use native password hasher, which auto-selects and migrates the best
        # possible hashing algorithm (which currently is "bcrypt")
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        
    firewalls:
        login:
            pattern: ^/api/v1/connexion
            stateless: true
            json_login:
                check_path: /api/v1/connexion
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                provider: app_user_provider
        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
    role_hierarchy:
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN_SIS:, ROLE_ADMIN_HOPITAL]  # Super Admin hérite de tous les droits
        ROLE_DOCTOR:     [ROLE_USER]  # Docteur hérite de ROLE_USER
        ROLE_PATIENT:  [ROLE_USER]  # Patient hérite de ROLE_USER
    access_control:
        - { path: ^/api/v1/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/urgencys, roles: PUBLIC_ACCESS }
        # - { path: ^/api/v1/main/powerbi/*, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: PUBLIC_ACCESS }
