framework:
framework:
    validation:
        enabled: true
        auto_mapping: true
        # Configuration correcte :
        mapping:
            paths:
                - '%kernel.project_dir%/src/Entity'