controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # config/routes.yaml

api_login_check:
    path: /api/v1/connexion
    methods: [POST]
